version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: egg_chart_prod
    command: gunicorn eggchart.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/egg_price/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
    user: egg_user

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/egg_price/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
